### PR TITLE
New Function ProgressBar() Contributed.

### PR DESCRIPTION
**Pull request by JAY-007-TRIVEDI**
This is new function which will print process for any long and time taken activity.

### CODE REVIEW

**Review by cloint — APPROVED** [review]
Thanks Jay !

**Comment by JAY-007-TRIVEDI** [comment]
T### **Test Case and Output of Functions : **
**Test Case For get_recent_filename()**
ls = ["Logs of Non-Adherence Report.txt", "Logs of DTS Report.txt"]
# Default Modified Mode
print("Recent Modified : ", get_recent_filename(file_list=ls))
# Created Mode
print("Recent Created File : ", get_recent_filename(file_list=ls, create=True))
# Accessed Mode
print("Recent Accessed File : ", get_recent_filename(file_list=ls, access=True))
# Return Error
print("Recent Accessed File : ", get_recent_filename(file_list=ls, create=True, access=True))
Output :
Recent Modified :  Logs of Non-Adherence Report.txt
Recent Created File :  Logs of Non-Adherence Report.txt
Recent Accessed File :  Logs of Non-Adherence Report.txt
ERROR in get_recent_filename() = Only One Mode is Allowed.
Recent Accessed File :  None
**Test Case For close_any_exe()**
close_any_exe(exe="whatsapp")
Output:
{'name': 'WhatsApp.exe'} Process Killed..
{'name': 'WhatsApp.exe'} Process Killed..
{'name': 'WhatsApp.exe'} Process Killed..
{'name': 'WhatsApp.exe'} Process Killed..
{'name': 'WhatsApp.exe'} Process Killed..
{'name': 'WhatsApp.exe'} Process Killed..
{'name': 'WhatsApp.exe'} Process Killed..

**Comment by karthik-kallur** [comment]
Remove the New Lines and Update Accordingly

**Comment by JAY-007-TRIVEDI** [comment]
I will do it ASAP.

**Comment by JAY-007-TRIVEDI** [comment]
Awesome, thanks!

**Pull request closed without merging**
